# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: performance

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Performance
        #if: github.event.pull_request.merged == true
        run: |
          ./gradlew benchmark
      - name: Save JMH results
        uses: actions/upload-artifact@v2
        with:
          name: jmh-results
          path: build/reports/jmh/results
      - name: Display JMH results as HTML
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: jmh-report
          path: build/reports/jmh/report
